# Generated by Django 5.0.7 on 2024-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0002_alter_empresas_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='estagio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='publico_alvo',
            field=models.CharField(choices=[('B2C', 'Business to Consumer'), ('B2B', 'Business to Business')], max_length=3),
        ),
    ]
